apiVersion: apps/v1
kind: Deployment
metadata:
  name: mon-app-deployment
  labels:
    app: mon-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mon-app
  template:
    metadata:
      labels:
        app: mon-app
    spec:
      containers:
        - name: mon-app-container
          image: node:latest
          ports:
            - containerPort: 3000
