apiVersion: v1
kind: Service
metadata:
  name: mon-app-service
  labels:
    app: mon-app
spec:
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: mon-app
  type: LoadBalancer
